# Generated by Django 3.0.7 on 2020-11-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(blank=True, help_text='Day of the event', null=True, verbose_name='Day of the event'),
        ),
    ]
