# Generated by Django 3.0.7 on 2020-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20201120_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(blank=True, help_text='Final time', null=True, verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.TimeField(blank=True, help_text='Starting time', null=True, verbose_name='Starting time'),
        ),
    ]
